/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#1b1b1b",
        "on-background": "#1a1c1c",
        "outline-variant": "#cfc4c5",
        "secondary-fixed-dim": "#c7c6c6",
        "surface-dim": "#dadada",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#848484",
        "tertiary-container": "#1b1b1b",
        "surface-tint": "#5e5e5e",
        "on-secondary-container": "#646464",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "surface-bright": "#f9f9f9",
        primary: "#000000",
        "primary-fixed": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "on-secondary-fixed": "#1b1c1c",
        tertiary: "#000000",
        "surface-variant": "#e2e2e2",
        "secondary-container": "#e3e2e2",
        "inverse-surface": "#2f3131",
        "secondary-fixed": "#e3e2e2",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        background: "#f9f9f9",
        error: "#ba1a1a",
        "inverse-on-surface": "#f0f1f1",
        "on-secondary-fixed-variant": "#464747",
        surface: "#F5F5F5",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "border-subtle": "#E5E5E5",
        secondary: "#5e5e5e",
        "on-primary-fixed": "#1b1b1b",
        "on-tertiary-fixed-variant": "#474747",
        outline: "#7e7576",
        "on-error": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "tertiary-fixed": "#e2e2e2",
        "inverse-primary": "#c6c6c6",
        "on-primary-container": "#848484",
        "tertiary-fixed-dim": "#c6c6c6",
        "text-muted": "#A3A3A3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "section-gap": "128px",
        "container-max": "1120px",
        "element-gap": "16px",
      },
      maxWidth: {
        "container-max": "1120px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        code: ["Courier Prime"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "display-lg-mobile": [
          "48px",
          {
            lineHeight: "52px",
            letterSpacing: "-0.03em",
            fontWeight: "700",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.05em",
            fontWeight: "500",
          },
        ],
        "display-lg": [
          "72px",
          {
            lineHeight: "80px",
            letterSpacing: "-0.04em",
            fontWeight: "700",
          },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        code: ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
